### ISSUE TITLE
Deputy Leader Promotion

### ISSUE THREAD

**Issue by ppxslz** [sapphireconquer/reportbugs#14]
Hi, i can't promote my members to deputy leaders and i still have slot to use it ,because i just have 3 deputys on my guild. The games says that it's full.

**Comment by ppxslz** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/63573829/79627309-8ab69180-810d-11ea-9134-24ec512cad59.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/63573829/79627310-8b4f2800-810d-11ea-9118-c81fe4222b5c.jpg)

**Comment by sapphireconquer** [comment]
It's working i tested!
