### ISSUE TITLE
Typing randomly deselects. Followed by chaos.

### ISSUE THREAD

**Issue by Shrinkidge** [sapphireconquer/reportbugs#16]
While typing on the bottom chat bar, VERY often the chat bar will sort of deselect itself. Then each letter pressed after that happens, opens different windows and quickly turns your game into a huge mess. Very aggravating when your trying to send a quick "thank you" and you end up rushing to close a bunch of windows before a mob gets you lol. Please take a look into this.

**Comment by sapphireconquer** [comment]
I tried and it happen somethings. Not sure where the cause it is. I think is client-side issue which cannot be fixed i think.

**Comment by Shrinkidge** [comment]
seems to happen when things pop up
such as, pvp events, sometimes xp skills etc.
