### ISSUE TITLE
XP ISSUE

### ISSUE THREAD

**Issue by ppttjj** [sapphireconquer/reportbugs#17]
I've leved a few warriors so it's way easier to see what this issue is.
Encountered it on LAB4 Minotaurs and have tried to see it on almost every level that I could (110 to 129), it probably happens on every other mob on the game.
Doesn't matter what gear you have, if you reach a certain x damage on mobs you get always a max xp bounty from killing it.
Tested it with adding/removing sdgs, srgs, goldprize.
[Album has images with more details](https://imgur.com/a/9Q01wbF)

So I think this means that everyone that reaches this x damage on mobs will have the same leveling time, I think that ppl with stronger gear should have better leveling times.

**Comment by sapphireconquer** [comment]
We supposed to have same rates only if players have same gears, only level contaains in xp giving. We have to add bp item calculation in that case and it wont be fair. So we baalanced the xp rate only by super rainbowgems and double / triple exp.
