### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by iagotorres3** [sapphireconquer/reportbugs#18]
Meteor Tear isnt upgrading items in TC.
Sash cant be discarded, becoming an annoyance at our warehouses.
Intensify skill not working.

**Comment by sapphireconquer** [comment]
1- Meteor Teaar is not supposed to upgrade items in TC.
2- Saash can be sold at Pharamacist / Storekeeper etc.
3- Will be fixxed.

**Comment by sapphireconquer** [comment]
Fixed Problem!
