### ISSUE TITLE
Xp Sheild Skill bugged

### ISSUE THREAD

**Issue by Shrinkidge** [sapphireconquer/reportbugs#30]
If you use the warrior xp shield skill and kill fast enough for it to pop up again it doesn't use the new time of the fresh xp shield skill. It will turn off after how ever many seconds were left on the previous shields.

**Comment by sapphireconquer** [comment]
I tested and it works perfectly.

**Comment by Shrinkidge** [comment]
wrong. test it using a stopwatch. start xp shield, let it get down to like 40 seconds, start another xp shield. the TIME says a New Time. but if you actually count down from what it was before you clicked the new shield, you will see that the shields vanish after 40 seconds, or whatever it was at.

come on man im trying to help you by reporting these. I really like your server and want it to do well.

**Comment by sapphireconquer** [comment]
Now it's fixxed!
