### ISSUE TITLE
Equipment Socket Bug

### ISSUE THREAD

**Issue by obreira** [sapphireconquer/reportbugs#35]
Hey. If my tao has any socket equipped is damage is almost null against players. If i use normal gear without sockets my damage is fine against players. Against mobs i don't have an issue with the socket gear.
![unknown](https://user-images.githubusercontent.com/42821882/80398732-018f1f80-88b0-11ea-9212-c2e1fbd247e4.png)

**Comment by sapphireconquer** [comment]
Fixed!
