### ISSUE TITLE
Some bugs (with suggestions)

### ISSUE THREAD

**Issue by iagotorres3** [sapphireconquer/reportbugs#39]
1. Headbands aren't being dropped from mobs. I socked one that I bought and wont be able to + it.
It would be interesting if helmets would be able to + it instead, so warriors would have option to choose between them without any problem when any + of them would drop.

2. Archers can't hit on Training Ground. It shoots 3 arrows then stops.

3. Tornado dmg, when leveled, is working weirdly, not gaining dmg or something like that. Same goes to Fire Meteor. When lvling it, the damage decreases.

4. BIG sized women are jumping slower than normal chars (at least when wearing 2 HANDED WEAPON).

5. Sometimes when a BIG warrior is wearing a shield and 1handed, when it jumps, the shield and 1handed gets bugged and the char's hair too (it gets bald).

**Comment by sapphireconquer** [comment]
Points 2, 3 has been fixed. Points 4 and 5 is a client side issue not dealing with in any circumstance, its about old jump. If we move to new jump issue will be fixed. Point 1 will be take in evidence soon. Thanks.
