### ISSUE TITLE
Magic defense % of armors / Super PhoenixGems Damage / Archers Damage

### ISSUE THREAD

**Issue by weberpr0** [sapphireconquer/reportbugs#41]
*Magic defense of armors is not working, i mean the % of each armor is giving the same.
*Super phoenix gems is not increasing the right magic atack, Flames added 1 SPG and the damage increase from 2765 to 2805, on this way don't worth working on 2 socs.
*Archers damage is kinda high, Zard got 14k damage by Freya, even without boots archers shouldnt do that damage lol.

**Comment by sapphireconquer** [comment]
Magic defence fixed. Super phoenix fixed. Archer dmg is correct.

**Comment by sapphireconquer** [comment]
Fixed!
