### ISSUE TITLE
Tornado vs Fire dmg and something else

### ISSUE THREAD

**Issue by iagotorres3** [sapphireconquer/reportbugs#42]
Hi.
My friend experienced something weird as a Fire tao.
As u can see on img files, his lvl 0 FIRE skill is only dealing 300 dmg less than his maxed lvl Tornado.
![fire lvl 0](https://user-images.githubusercontent.com/63910971/82254026-793cf100-9928-11ea-8bbe-de18ea8cf2c8.png)

This is a picture of the dealing dmg as using Fire:
![fire 2426 dmg](https://user-images.githubusercontent.com/63910971/82254067-8ce85780-9928-11ea-8181-a3bb66398468.png)

This is a picture of the dealing dmg as using Fixed Tornado:
![fixed nado 2743 dmg](https://user-images.githubusercontent.com/63910971/82254104-a12c5480-9928-11ea-8f38-cd14f1e39e4b.png)

I got some pics of a table chart from CO website where it shows the values of both skills, and it doesnt seems reasonable that despite such a huge difference on values, it only differs 300 dmg in the end.

![fire skill values](https://user-images.githubusercontent.com/63910971/82254245-e0f33c00-9928-11ea-8675-6793d3c2c205.PNG)

![nado skill values](https://user-images.githubusercontent.com/63910971/82254266-e81a4a00-9928-11ea-9dc8-a19eeebc7244.PNG)

PS: SUPER MOON GEM is giving 50 M-ATTACK, im not sure if its normal, but its just something i realized and wanted to share with u, maybe its a bug, maybe its not.

**Comment by sapphireconquer** [comment]
This point has been touched and modified.
